package domain.aspectwords;

import domain.entity.AspectWords;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Parses a list of aspect words from a text file that has been generated by Hadoop.
 */
public class HadoopAspectWordsParser implements AspectWordsParser {

    /**
     * {@inheritDoc}
     */
    @Override
    public AspectWords parse(String aspectWordsFilePath) {

        try {
            List<String> aspectWords = new ArrayList<>();

            BufferedReader bufferedReader = new BufferedReader(new FileReader(aspectWordsFilePath));

            String line;
            while ((line = bufferedReader.readLine()) != null) {
                String[] split = line.split("\\s+");
                aspectWords.add(split[0]);
            }

            if (aspectWords.size() == 0) {
                throw new IllegalArgumentException("File does not contain any aspect words.");
            }

            return new AspectWords(aspectWords);

        } catch(IOException ex) {
            throw new IllegalArgumentException(ex.getMessage());
        }
    }
}
